def get_mock_library_data():
    """
    Returns realistic mock library data for Incheon libraries.
    This is used as a fallback if the API call fails or no API key is set.
    """
    return [
        {
            "LBRRY_NM": "인천광역시 미추홀도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "남동구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 월요일 및 법정공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "09:00",
            "PLHLDY_OPER_END_TM": "17:00",
            "PRSL_SEAT_CNT": 850,
            "BOOK_CNT": 320000,
            "CTNU_PBLCTN_CNT": 120,
            "NONBK_CNT": 15000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 15,
            "LCTN_ROAD_NM_ADDR": "인천광역시 남동구 예술로 192번길 56",
            "OPER_INST_NM": "인천광역시청",
            "LBRRY_TELNO": "032-462-3900",
            "PLOT_AREA": 12500,
            "BLDG_AREA": 6500,
            "HMPG_ADDR": "https://www.incheon.go.kr/michuhol",
            "LAT": 37.4478,
            "LOT": 126.7012,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시립 수봉도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "미추홀구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 월요일 및 국경일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 350,
            "BOOK_CNT": 125000,
            "CTNU_PBLCTN_CNT": 80,
            "NONBK_CNT": 8000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 미추홀구 수봉안길 84",
            "OPER_INST_NM": "인천문화재단",
            "LBRRY_TELNO": "032-870-9100",
            "PLOT_AREA": 4500,
            "BLDG_AREA": 2800,
            "HMPG_ADDR": "https://www.imla.kr/subong",
            "LAT": 37.4612,
            "LOT": 126.6621,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시 부평도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "부평구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 수요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "09:00",
            "PLHLDY_OPER_END_TM": "17:00",
            "PRSL_SEAT_CNT": 600,
            "BOOK_CNT": 260000,
            "CTNU_PBLCTN_CNT": 150,
            "NONBK_CNT": 12000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 부평구 안남로 39",
            "OPER_INST_NM": "인천광역시교육청",
            "LBRRY_TELNO": "032-510-2400",
            "PLOT_AREA": 8200,
            "BLDG_AREA": 4500,
            "HMPG_ADDR": "https://lib.ice.go.kr/bupyeong",
            "LAT": 37.4912,
            "LOT": 126.7214,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시 서구도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "서구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 화요일 및 일요일을 제외한 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "09:00",
            "PLHLDY_OPER_END_TM": "17:00",
            "PRSL_SEAT_CNT": 480,
            "BOOK_CNT": 210000,
            "CTNU_PBLCTN_CNT": 95,
            "NONBK_CNT": 9000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 서구 서달로 74번길 16",
            "OPER_INST_NM": "인천광역시교육청",
            "LBRRY_TELNO": "032-585-7100",
            "PLOT_AREA": 6400,
            "BLDG_AREA": 3600,
            "HMPG_ADDR": "https://lib.ice.go.kr/seogu",
            "LAT": 37.5451,
            "LOT": 126.6789,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시 계양도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "계양구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 목요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "09:00",
            "PLHLDY_OPER_END_TM": "17:00",
            "PRSL_SEAT_CNT": 520,
            "BOOK_CNT": 195000,
            "CTNU_PBLCTN_CNT": 110,
            "NONBK_CNT": 9500,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 계양구 계산새로 87",
            "OPER_INST_NM": "인천광역시교육청",
            "LBRRY_TELNO": "032-540-4400",
            "PLOT_AREA": 7100,
            "BLDG_AREA": 4100,
            "HMPG_ADDR": "https://lib.ice.go.kr/gyeyang",
            "LAT": 37.5385,
            "LOT": 126.7368,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "송도국제기구도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "연수구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 토, 일요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "18:00",
            "SAT_OPER_BGNG_TM": "00:00",
            "SAT_OPER_END_TM": "00:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 100,
            "BOOK_CNT": 55000,
            "CTNU_PBLCTN_CNT": 30,
            "NONBK_CNT": 2000,
            "LOAN_PSBLTY_VLMCNT": 3,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 연수구 아트센터대로 175 G타워 민원동 2층",
            "OPER_INST_NM": "연수구청",
            "LBRRY_TELNO": "032-749-8250",
            "PLOT_AREA": 2000,
            "BLDG_AREA": 800,
            "HMPG_ADDR": "https://www.yeonsu.go.kr/lib",
            "LAT": 37.3854,
            "LOT": 126.6418,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시립 율목도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "중구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 화요일 및 국가공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 240,
            "BOOK_CNT": 85000,
            "CTNU_PBLCTN_CNT": 60,
            "NONBK_CNT": 4000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 중구 율목로38번길 2-2",
            "OPER_INST_NM": "인천문화재단",
            "LBRRY_TELNO": "032-770-3800",
            "PLOT_AREA": 3800,
            "BLDG_AREA": 1900,
            "HMPG_ADDR": "https://www.imla.kr/yulmok",
            "LAT": 37.4725,
            "LOT": 126.6315,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시립 영종도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "중구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 금요일 및 국가공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 210,
            "BOOK_CNT": 78000,
            "CTNU_PBLCTN_CNT": 50,
            "NONBK_CNT": 3500,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 중구 운남서로 100-1",
            "OPER_INST_NM": "인천문화재단",
            "LBRRY_TELNO": "032-745-6000",
            "PLOT_AREA": 4100,
            "BLDG_AREA": 2200,
            "HMPG_ADDR": "https://www.imla.kr/yjlib",
            "LAT": 37.4891,
            "LOT": 126.5612,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시 강화도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "강화군",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 월요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "18:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "17:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 180,
            "BOOK_CNT": 92000,
            "CTNU_PBLCTN_CNT": 40,
            "NONBK_CNT": 3000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 강화군 강화읍 강화대로 373",
            "OPER_INST_NM": "강화군청",
            "LBRRY_TELNO": "032-930-3571",
            "PLOT_AREA": 3100,
            "BLDG_AREA": 1500,
            "HMPG_ADDR": "https://www.ganghwa.go.kr/open_content/library/",
            "LAT": 37.7465,
            "LOT": 126.4862,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "논현작은도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "남동구",
            "LBRRY_TYPE": "작은도서관",
            "CLSDY_GUID": "매주 일요일 및 법정공휴일",
            "WKDAY_OPER_BGNG_TM": "10:00",
            "WKDAY_OPER_END_TM": "17:00",
            "SAT_OPER_BGNG_TM": "10:00",
            "SAT_OPER_END_TM": "14:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 30,
            "BOOK_CNT": 15000,
            "CTNU_PBLCTN_CNT": 5,
            "NONBK_CNT": 200,
            "LOAN_PSBLTY_VLMCNT": 3,
            "LOAN_PSBLTY_DCO": 7,
            "LCTN_ROAD_NM_ADDR": "인천광역시 남동구 논현고잔로 135",
            "OPER_INST_NM": "논현동 주민자치회",
            "LBRRY_TELNO": "032-453-6480",
            "PLOT_AREA": 100,
            "BLDG_AREA": 100,
            "HMPG_ADDR": "https://www.namdong.go.kr/smalllib",
            "LAT": 37.4045,
            "LOT": 126.7225,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "구월어린이도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "남동구",
            "LBRRY_TYPE": "어린이도서관",
            "CLSDY_GUID": "매주 금요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "18:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "17:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 120,
            "BOOK_CNT": 48000,
            "CTNU_PBLCTN_CNT": 20,
            "NONBK_CNT": 1500,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 남동구 용천로 94",
            "OPER_INST_NM": "남동구도시관리공단",
            "LBRRY_TELNO": "032-453-5730",
            "PLOT_AREA": 1200,
            "BLDG_AREA": 850,
            "HMPG_ADDR": "https://www.namdonglib.go.kr",
            "LAT": 37.4589,
            "LOT": 126.7118,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "청라국제도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "서구",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 월요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "22:00",
            "SAT_OPER_BGNG_TM": "09:00",
            "SAT_OPER_END_TM": "18:00",
            "PLHLDY_OPER_BGNG_TM": "09:00",
            "PLHLDY_OPER_END_TM": "17:00",
            "PRSL_SEAT_CNT": 320,
            "BOOK_CNT": 110000,
            "CTNU_PBLCTN_CNT": 70,
            "NONBK_CNT": 5000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 서구 담지로 8번길 5",
            "OPER_INST_NM": "인천광역시 미추홀도서관 분관",
            "LBRRY_TELNO": "032-562-1875",
            "PLOT_AREA": 3500,
            "BLDG_AREA": 1800,
            "HMPG_ADDR": "https://www.incheon.go.kr/michuhol/MC040101",
            "LAT": 37.5342,
            "LOT": 126.6534,
            "DATA_CRTR_YMD": "20240101"
        },
        {
            "LBRRY_NM": "인천광역시 옹진군립 영흥도서관",
            "CTPV_NM": "인천광역시",
            "SGG_NM": "옹진군",
            "LBRRY_TYPE": "공공도서관",
            "CLSDY_GUID": "매주 토, 일요일 및 공휴일",
            "WKDAY_OPER_BGNG_TM": "09:00",
            "WKDAY_OPER_END_TM": "18:00",
            "SAT_OPER_BGNG_TM": "00:00",
            "SAT_OPER_END_TM": "00:00",
            "PLHLDY_OPER_BGNG_TM": "00:00",
            "PLHLDY_OPER_END_TM": "00:00",
            "PRSL_SEAT_CNT": 80,
            "BOOK_CNT": 32000,
            "CTNU_PBLCTN_CNT": 15,
            "NONBK_CNT": 1000,
            "LOAN_PSBLTY_VLMCNT": 5,
            "LOAN_PSBLTY_DCO": 14,
            "LCTN_ROAD_NM_ADDR": "인천광역시 옹진군 영흥면 영흥로251번길 90",
            "OPER_INST_NM": "옹진군청",
            "LBRRY_TELNO": "032-899-3890",
            "PLOT_AREA": 1500,
            "BLDG_AREA": 600,
            "HMPG_ADDR": "https://www.ongjin.go.kr/open_content/library/",
            "LAT": 37.2523,
            "LOT": 126.4956,
            "DATA_CRTR_YMD": "20240101"
        }
    ]
